application: longbrrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
- url: /favicon\.png
  mime_type: image/png
  static_files: static/favicon.png
  upload: static/favicon\.png

- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /crossdomain.xml
  mime_type: text/x-cross-domain-policy
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /(.*\.xml)
  mime_type: text/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /assets/fonts/(.*\.otf)
  mime_type: application/x-font-otf
  static_files: assets/fonts/\1
  upload: assets/fonts/(.*\.otf)

- url: /assets
  static_dir: assets

- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: .*
  script: main.app

skip_files:
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.pyc
- ^(.*/)?.*\.db

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: latest

builtins:
- deferred: on